spring:
  datasource:
    hikari:
      maximumPoolSize: 10
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=collmobilePPU2
    username: elkana911
    password: elkana911
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  output:
    ansi:
      enabled: DETECT
  sql:
    init:
      mode: always
      # biar ga cerewet di mssql
      continue-on-error: true
      # penggunaan platform memungkinkan beda script xxx-mssql.sql utk masing2 platform
      platform: mssql
      data-locations:
      - classpath*:*.sql


