spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.205.101:1521:jtofast
    username: fapi
    password: fapi
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  output:
    ansi:
      enabled: DETECT
  sql:
    init:
      mode: always
      # biar ga cerewet di mssql
      continue-on-error: true
      # penggunaan platform memungkinkan beda script xxx-mssql.sql utk masing2 platform
      platform: oracle
      data-locations:
      - classpath*:*.sql
