spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ppidmprd:3306/idm?autoReconnect=true&useSSL=false&serverTimezone=Asia/Jakarta
    username: fapi
    password: fapi
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  output:
    ansi:
      enabled: DETECT
  sql:
    init:
      mode: always
      # biar ga cerewet di mssql
      continue-on-error: true
      # penggunaan platform memungkinkan beda script xxx-mssql.sql utk masing2 platform
      platform: mysql
      data-locations:
      - classpath*:*.sql